### ISSUE TITLE
Can't load variable from cloud platform

### ISSUE THREAD

**Issue by benshumaker** [varse-io/varse#3]
ERROR
Cannot read properties of null (reading 'value')
TypeError: Cannot read properties of null (reading 'value')
    at VarseClient.get (http://localhost:3100/static/js/bundle.js:46587:26)
    at async VarseClient.getBool (http://localhost:3100/static/js/bundle.js:46590:19)
ERROR
Cannot read properties of null (reading 'value')
TypeError: Cannot read properties of null (reading 'value')
    at VarseClient.get (http://localhost:3100/static/js/bundle.js:46587:26)
    at async VarseClient.getBool (http://localhost:3100/static/js/bundle.js:46590:19)
    
```tsx
import Navbar from '../../library/Navbar/Navbar'
import Button from '../../library/Button/Button'
import { useVarseBool } from 'varse-io-react'

const Home: React.FC = () => {
  const isNavbarVisible = useVarseBool('new-variable')
  console.log(isNavbarVisible)

  return (
    <div className="relative min-h-screen w-full flex flex-col items-center justify-center px-8">
      {isNavbarVisible && <Navbar />}
      <div className="flex flex-col items-center max-w-[600px]">
        <h1 className="mb-6 text-h1 text-text-1 text-center">
          Manage Server Variables at Runtime
        </h1>
        <p className="mb-16 text-subtitle text-text-2 text-center max-w-[500px]">
          Varse is a minimal tool for updating configurations without deploying.
          It has versatile applications, including feature flags, A/B tests, and
          deployment controls.
        </p>
        <div className="flex gap-4">
          <a href="https://github.com/varse-io/varse">
            <Button theme="outline">Documentation</Button>
          </a>
          <a href={`${process.env.REACT_APP_VARSE_APP_URL}/signup`}>
            <Button>Start Building</Button>
          </a>
        </div>
      </div>
    </div>
  )
}

export default Home
```

![image](https://github.com/user-attachments/assets/9578580d-1c0c-42f1-b29d-2e493893844d)

**Comment by izakfr** [comment]
It looks like the variable name is incorrect, should be `new_variable` not `new-variable`. I'll make an update to the SDK to make the error more clear.

**Comment by izakfr** [comment]
A new version of the SDK has been published with this fix. Please `run npm / bun update` to get the v1.1.4 sdk.

**Comment by benshumaker** [comment]
I pulled the new sdk version, but I have the same error
<img width="1440" alt="Screenshot 2024-11-04 at 12 18 37 PM" src="https://github.com/user-attachments/assets/0adb8d0f-f6ba-496d-9852-826df8789b34">
<img width="1440" alt="Screenshot 2024-11-04 at 12 18 47 PM" src="https://github.com/user-attachments/assets/0f4bef7f-2e28-4eb6-a395-a98b2f02b147">

**Comment by izakfr** [comment]
It looks like varse-io is still on version 1.1.3. Can you run bun update so that it's on 1.1.4?

**Comment by benshumaker** [comment]
I already ran bun update, but I still get this error

**Comment by izakfr** [comment]
Have you updated the variable name to be correct? That should fix the problem. I'll create a new ticket and investigate to solve the error message.

**Comment by izakfr** [comment]
https://github.com/varse-io/varse/issues/6
